module.exports = {
	home: {
		onUkraine: 'Маршрути по Україні',
		abroad: 'Маршрути за кордон',
	},
	ukraine: {
		ternopil: 'Тернопільська обл.',
		lviv: 'Львівська обл.',
		lytsk: 'Волинська обл.',
		rivne: 'Рівненська обл.',
		kuiv: 'Київська обл.',
		vinnutsa: 'Вінницька обл.',
		dnipro: 'Дніпропетровська обл.',
		khmelnytsk: 'Хмельницька обл.',
		zakarpatya: 'Закарпатська обл.',
		frankivsk: 'Івано-Франківська обл.',
		zytomyr: 'Житомирська обл.',
		chernivci: 'Чернівецька обл.',
		cherkasy: 'Черкаська обл.',
		chernigiv: 'Чернігівська обл.',
		poltava: 'Полтавська обл.',
		kharkiv: 'Харківська обл.',
		symu: 'Сумська обл.',
		mykolaiv: 'Миколаївська обл.',
		zapirizia: 'Запорізька обл.',
		odesa: 'Одеська обл.',
		kirovograd: 'Кіровоградська обл.',
		kherson: 'Херсонська обл.',
	},
	abroad: {
		italia: 'Італія',
		germany: 'Німеччина',
		poland: 'Польща',
		rymynia: 'Румунія',
		lutva: 'Литва',
	},
	back: {
		backs: 'Назад',
	},
	info: {
		info: 'Інформація',
	},
}
